const DATA_URL='https://raw.githubusercontent.com/midvash/bible-data/main/versions/en/kjv/kjv.json';
const BOOKS=[
['Genesis',50,'OT'],['Exodus',40,'OT'],['Leviticus',27,'OT'],['Numbers',36,'OT'],['Deuteronomy',34,'OT'],['Joshua',24,'OT'],['Judges',21,'OT'],['Ruth',4,'OT'],['1 Samuel',31,'OT'],['2 Samuel',24,'OT'],['1 Kings',22,'OT'],['2 Kings',25,'OT'],['1 Chronicles',29,'OT'],['2 Chronicles',36,'OT'],['Ezra',10,'OT'],['Nehemiah',13,'OT'],['Esther',10,'OT'],['Job',42,'OT'],['Psalms',150,'OT'],['Proverbs',31,'OT'],['Ecclesiastes',12,'OT'],['Song of Solomon',8,'OT'],['Isaiah',66,'OT'],['Jeremiah',52,'OT'],['Lamentations',5,'OT'],['Ezekiel',48,'OT'],['Daniel',12,'OT'],['Hosea',14,'OT'],['Joel',3,'OT'],['Amos',9,'OT'],['Obadiah',1,'OT'],['Jonah',4,'OT'],['Micah',7,'OT'],['Nahum',3,'OT'],['Habakkuk',3,'OT'],['Zephaniah',3,'OT'],['Haggai',2,'OT'],['Zechariah',14,'OT'],['Malachi',4,'OT'],['Matthew',28,'NT'],['Mark',16,'NT'],['Luke',24,'NT'],['John',21,'NT'],['Acts',28,'NT'],['Romans',16,'NT'],['1 Corinthians',16,'NT'],['2 Corinthians',13,'NT'],['Galatians',6,'NT'],['Ephesians',6,'NT'],['Philippians',4,'NT'],['Colossians',4,'NT'],['1 Thessalonians',5,'NT'],['2 Thessalonians',3,'NT'],['1 Timothy',6,'NT'],['2 Timothy',4,'NT'],['Titus',3,'NT'],['Philemon',1,'NT'],['Hebrews',13,'NT'],['James',5,'NT'],['1 Peter',5,'NT'],['2 Peter',3,'NT'],['1 John',5,'NT'],['2 John',1,'NT'],['3 John',1,'NT'],['Jude',1,'NT'],['Revelation',22,'NT']];
let bible=null,currentBook=0,currentChapter=1;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));closeDrawer();window.scrollTo({top:0,behavior:'smooth'});if(id==='bookmarks')renderBookmarks();if(id==='notes')renderNotes();}
function openDrawer(){$('#drawer').classList.add('open');$('#scrim').classList.add('show');$('#drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#scrim').classList.remove('show');$('#drawer').setAttribute('aria-hidden','true')}
function save(key,val){localStorage.setItem(key,JSON.stringify(val))}function load(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function renderBooks(filter=''){const q=filter.trim().toLowerCase();$('#booksGrid').innerHTML=BOOKS.map((b,i)=>({b,i})).filter(x=>x.b[0].toLowerCase().includes(q)).map(({b,i})=>`<button class="book-card" data-book="${i}"><b>${b[0]}</b><small>${b[1]} chapter${b[1]===1?'':'s'} • ${b[2]==='OT'?'Old':'New'} Testament</small></button>`).join('');$$('[data-book]').forEach(btn=>btn.onclick=()=>openBook(+btn.dataset.book,1));}
async function loadBible(){if(bible)return bible;const cached=load('ymb_bible_cache',null);if(cached?.books?.length===66){bible=cached;return bible}try{const r=await fetch(DATA_URL,{cache:'force-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const raw=await r.json();bible=normalize(raw);if(bible.books.length!==66)throw new Error('Incomplete Bible data');try{save('ymb_bible_cache',bible)}catch(e){console.info('Bible too large for localStorage; browser cache will be used.')}return bible}catch(e){throw new Error('Bible text could not be loaded. Check your internet connection and try again.');}}
function normalize(raw){const rb=Array.isArray(raw)?raw:(raw.books||[]);return{books:rb.map((b,bi)=>({name:b.englishName||b.name||b.book||BOOKS[bi]?.[0]||`Book ${bi+1}`,chapters:(b.chapters||[]).map((c,ci)=>({number:+(c.chapter||c.number||ci+1),verses:(c.verses||[]).map((v,vi)=>({number:+(v.number||v.verse||vi+1),text:String(v.text||'').trim()}))}))}))}}
async function openBook(bookIndex,chapter=1){currentBook=bookIndex;currentChapter=chapter;showView('reader');$('#readerTitle').textContent=BOOKS[bookIndex][0];$('#readerTestament').textContent=BOOKS[bookIndex][2]==='OT'?'OLD TESTAMENT':'NEW TESTAMENT';$('#chapterSelect').innerHTML=Array.from({length:BOOKS[bookIndex][1]},(_,i)=>`<option value="${i+1}" ${i+1===chapter?'selected':''}>Chapter ${i+1}</option>`).join('');$('#readerStatus').textContent='Loading chapter…';$('#verses').innerHTML='';try{const data=await loadBible();const book=findBook(data,BOOKS[bookIndex][0],bookIndex);const ch=book?.chapters?.[chapter-1];if(!ch)throw new Error('Chapter not found in Bible data.');$('#readerStatus').textContent='';renderVerses(book,chapter,ch.verses||[]);}catch(e){$('#readerStatus').textContent=e.message;}}
function findBook(data,name,index){const simplify=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'').replace(/^psalms$/,'psalm');const target=simplify(name);return data.books.find(b=>simplify(b.name)===target)||data.books[index];}
function renderVerses(book,chapter,verses){const marks=load('ymb_bookmarks');$('#verses').innerHTML=verses.map(v=>{const ref=`${BOOKS[currentBook][0]} ${chapter}:${v.number}`,marked=marks.some(x=>x.ref===ref);return `<article class="verse"><span class="num">${v.number}</span><span>${escapeHtml(v.text)}</span><div class="verse-actions"><button data-mark="${encodeURIComponent(ref)}" data-text="${encodeURIComponent(v.text)}">${marked?'✓ Saved':'🔖 Bookmark'}</button><button data-note="${encodeURIComponent(ref)}" data-text="${encodeURIComponent(v.text)}">📝 Note</button></div></article>`}).join('');bindVerseActions();}
function bindVerseActions(){$$('[data-mark]').forEach(b=>b.onclick=()=>toggleBookmark(decodeURIComponent(b.dataset.mark),decodeURIComponent(b.dataset.text),b));$$('[data-note]').forEach(b=>b.onclick=()=>addNote(decodeURIComponent(b.dataset.note),decodeURIComponent(b.dataset.text)));}
function toggleBookmark(ref,text,btn){let a=load('ymb_bookmarks');const i=a.findIndex(x=>x.ref===ref);if(i>=0){a.splice(i,1);btn.textContent='🔖 Bookmark'}else{a.unshift({ref,text,at:Date.now()});btn.textContent='✓ Saved'}save('ymb_bookmarks',a)}
function addNote(ref,text){const old=load('ymb_notes');const existing=old.find(x=>x.ref===ref);const note=prompt(`Note for ${ref}:`,existing?.note||'');if(note===null)return;const next=old.filter(x=>x.ref!==ref);if(note.trim())next.unshift({ref,text,note:note.trim(),at:Date.now()});save('ymb_notes',next);}
function renderBookmarks(){const a=load('ymb_bookmarks');$('#bookmarkList').innerHTML=a.length?a.map((x,i)=>`<article class="result-card"><strong>${escapeHtml(x.ref)}</strong><p>${escapeHtml(x.text)}</p><div class="result-actions"><button data-delmark="${i}">Remove</button></div></article>`).join(''):'<div class="status">No bookmarks yet. Save verses while reading.</div>';$$('[data-delmark]').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.delmark,1);save('ymb_bookmarks',a);renderBookmarks()})}
function renderNotes(){const a=load('ymb_notes');$('#noteList').innerHTML=a.length?a.map((x,i)=>`<article class="result-card"><strong>${escapeHtml(x.ref)}</strong><p>${escapeHtml(x.text)}</p><p><b>Your note:</b> ${escapeHtml(x.note)}</p><div class="result-actions"><button data-editnote="${i}">Edit</button><button data-delnote="${i}">Delete</button></div></article>`).join(''):'<div class="status">No notes yet.</div>';$$('[data-editnote]').forEach(b=>b.onclick=()=>{const x=a[+b.dataset.editnote];addNote(x.ref,x.text);renderNotes()});$$('[data-delnote]').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.delnote,1);save('ymb_notes',a);renderNotes()})}
async function searchBible(q){q=q.trim();if(!q)return;$('#searchStatus').textContent='Loading and searching the Bible…';$('#searchResults').innerHTML='';try{const data=await loadBible();const exact=q.match(/^(.+?)\s+(\d+)(?::(\d+))?$/);if(exact){const name=exact[1].trim(),chap=+exact[2],verse=exact[3]?+exact[3]:null;const bi=BOOKS.findIndex(b=>b[0].toLowerCase()===name.toLowerCase()||b[0].toLowerCase().startsWith(name.toLowerCase()));if(bi>=0&&chap>=1&&chap<=BOOKS[bi][1]){if(!verse){openBook(bi,chap);return}const book=findBook(data,BOOKS[bi][0],bi),v=book?.chapters?.[chap-1]?.verses?.find(x=>x.number===verse);if(v){renderSearchResults([{ref:`${BOOKS[bi][0]} ${chap}:${verse}`,text:v.text}]);$('#searchStatus').textContent='1 verse found.';return}}}const s=q.toLowerCase();const hits=[];outer:for(let bi=0;bi<data.books.length;bi++)for(let ci=0;ci<data.books[bi].chapters.length;ci++)for(const v of data.books[bi].chapters[ci].verses){if(v.text.toLowerCase().includes(s)){hits.push({ref:`${BOOKS[bi]?.[0]||data.books[bi].name} ${ci+1}:${v.number}`,text:v.text});if(hits.length>=100)break outer}}$('#searchStatus').textContent=hits.length?`${hits.length}${hits.length===100?'+':''} result(s).`:'No matching verses found.';renderSearchResults(hits);}catch(e){$('#searchStatus').textContent=e.message;}}
function renderSearchResults(hits){$('#searchResults').innerHTML=hits.map(x=>`<article class="result-card"><strong>${escapeHtml(x.ref)}</strong><p>${escapeHtml(x.text)}</p><div class="result-actions"><button data-mark="${encodeURIComponent(x.ref)}" data-text="${encodeURIComponent(x.text)}">🔖 Bookmark</button><button data-note="${encodeURIComponent(x.ref)}" data-text="${encodeURIComponent(x.text)}">📝 Note</button></div></article>`).join('');bindVerseActions();}
function setDaily(){const list=[['Psalm 119:105','Thy word is a lamp unto my feet, and a light unto my path.'],['Proverbs 3:5','Trust in the LORD with all thine heart; and lean not unto thine own understanding.'],['Philippians 4:13','I can do all things through Christ which strengtheneth me.'],['Psalm 56:3','What time I am afraid, I will trust in thee.']];const x=list[Math.floor(Date.now()/86400000)%list.length];$('#dailyVerse').textContent=`“${x[1]}”`;$('#dailyRef').textContent=x[0]+' • KJV';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#menuBtn').onclick=openDrawer;$('#scrim').onclick=closeDrawer;$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('ymb_theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('ymb_theme')==='dark')document.body.classList.add('dark');$('#bookFilter').oninput=e=>renderBooks(e.target.value);$('#chapterSelect').onchange=e=>openBook(currentBook,+e.target.value);$('#backBooks').onclick=()=>showView('books');$('#searchForm').onsubmit=e=>{e.preventDefault();searchBible($('#searchInput').value)};renderBooks();setDaily();showView('home');
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
